const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");

const users = [
    {
        _id: mongoose.Types.ObjectId("569ed8269353e9f4c51617ab"),
        firstName: "Alex",
        lastName: "Jimenez",
        username: "radikalex",
        email: "alex@gmail.com",
        password: bcrypt.hashSync("123456", 10),
        user_img: "users_images/default/seeder1.jpg",
        darkMode: true,
        bio: "Prefiero\nVue\nen\nverdad",
        role: "user",
        followers: [
            mongoose.Types.ObjectId("569ed8269353e9f4c51617ac"),
            mongoose.Types.ObjectId("569ed8269353e9f4c51617ae"),
        ],
        following: [
            mongoose.Types.ObjectId("569ed8269353e9f4c51617ac"),
            mongoose.Types.ObjectId("569ed8269353e9f4c51617ae"),
            mongoose.Types.ObjectId("569ed8269353e9f4c51617af"),
            mongoose.Types.ObjectId("569ed8269353e9f4c51617f1"),
            mongoose.Types.ObjectId("569ed8269353e9f4c51617f2"),
        ],
        confirmed: true,
        tokens: [],
        postIds: [
            mongoose.Types.ObjectId("569ed8269353e9f4c51617b1"),
            mongoose.Types.ObjectId("569ed8269353e9f4c51617b2"),
        ],
    },
    {
        _id: mongoose.Types.ObjectId("569ed8269353e9f4c51617ac"),
        firstName: "Ivan",
        lastName: "Jimenez",
        username: "voltron",
        email: "ivan@gmail.com",
        password: bcrypt.hashSync("123456", 10),
        user_img: "users_images/default/seeder2.jpg",
        darkMode: false,
        bio: "Videojuegos y anime",
        role: "user",
        followers: [mongoose.Types.ObjectId("569ed8269353e9f4c51617ab")],
        following: [],
        confirmed: true,
        tokens: [],
        postIds: [],
    },
    {
        _id: mongoose.Types.ObjectId("569ed8269353e9f4c51617ad"),
        firstName: "Sif",
        lastName: "Et tabaa",
        username: "sif",
        email: "sif@gmail.com",
        password: bcrypt.hashSync("123456", 10),
        user_img: "users_images/default/seeder3.jpg",
        darkMode: false,
        bio: "Deporte, anime y motivación",
        role: "user",
        followers: [],
        following: [],
        confirmed: true,
        tokens: [],
        postIds: [],
    },
    {
        _id: mongoose.Types.ObjectId("569ed8269353e9f4c51617ae"),
        firstName: "Sergio",
        lastName: "Juan Vidal",
        username: "Wonders",
        email: "sergio@gmail.com",
        password: bcrypt.hashSync("123456", 10),
        user_img: "users_images/default/seeder4.jpg",
        darkMode: false,
        bio: "Me ha vuelto a intear el support",
        role: "user",
        followers: [mongoose.Types.ObjectId("569ed8269353e9f4c51617ab")],
        following: [mongoose.Types.ObjectId("569ed8269353e9f4c51617ab")],
        confirmed: true,
        tokens: [],
        postIds: [],
    },
    {
        _id: mongoose.Types.ObjectId("569ed8269353e9f4c51617af"),
        firstName: "Sofia",
        lastName: "Pinilla",
        username: "SofiaPinilla",
        email: "sofia@gmail.com",
        password: bcrypt.hashSync("123456", 10),
        user_img: "users_images/default/seeder5.jpg",
        darkMode: false,
        bio: "Programación, anime y chistes malos\nExámenes sorpresa de lunes a viernes",
        role: "user",
        followers: [mongoose.Types.ObjectId("569ed8269353e9f4c51617ab")],
        following: [],
        confirmed: true,
        tokens: [],
        postIds: [],
    },
    {
        _id: mongoose.Types.ObjectId("569ed8269353e9f4c51617f1"),
        firstName: "Matías",
        lastName: "Salvatore",
        username: "msalvatore82",
        email: "matias@gmail.com",
        password: bcrypt.hashSync("123456", 10),
        user_img: "users_images/default/seeder6.jpg",
        darkMode: false,
        bio: "Desarrollador FullStack\nAntes muerto que poner una línea de CSS",
        role: "user",
        followers: [mongoose.Types.ObjectId("569ed8269353e9f4c51617ab")],
        following: [],
        confirmed: true,
        tokens: [],
        postIds: [],
    },
    {
        _id: mongoose.Types.ObjectId("569ed8269353e9f4c51617f2"),
        firstName: "Fede",
        lastName: "Arévalo",
        username: "Fede-Arevalo",
        email: "fede@gmail.com",
        password: bcrypt.hashSync("123456", 10),
        user_img: "users_images/default/seeder7.jpg",
        darkMode: false,
        bio: "Che, cafesito?",
        role: "user",
        followers: [mongoose.Types.ObjectId("569ed8269353e9f4c51617ab")],
        following: [],
        confirmed: true,
        tokens: [],
        postIds: [],
    },
];

module.exports = {
    users,
};
